users:
    name: users
    fields:
        email:
            type: string
        password:
            type: string

locations:
    name: locations
    fields:
        name:
            type: text
        pin:
            type: point
        state_name:
            type: text
        state_code:
            type: text
        street:
            type: text
        zipcode:
            type: text
        housenumber:
            type: text
    relations:
        users:
            type: belongsTo
        machines:
            type: hasMany

machines:
    name: machines
    fields:
        name:
            type: text
        rating:
            type: text
        votes:
            type: text

notes:
    name: notes
    fields:
        note:
            type: string
        type:
            type: string

rates:
    name: rates
    fields:
        price:
            type: float
        games:
            type: float

cities:
    name: cities
    fields:
        name:
            type: text

countries:
    name: countries
    fields:
        name:
            type: text
        code:
            type: text
