var a = [ { city: 'Berlin',
    zipcode: '10243',
    place: 'EFK-Kart&EventsenterBerlin(1StockwerkunterEastsideBowling)',
    machine: 'AddamsFamily',
    address: 'Koppenstraße8(Ostbahnhof)',
    stars: 1,
    note: 'SehrungepflegtesGerät;kaumSpielbar',
    lastupdate: '2010-05-23',
    pin: { type: 'Point', coordinates: [ 13.4343831, 52.5128869 ] },
    country: 'Germany',
    street: 'Koppenstraße',
    number: '8' },
  { city: 'Berlin',
    zipcode: '10243',
    place: 'EFK-Kart&EventsenterBerlin(1StockwerkunterEastsideBowling)',
    machine: 'NBAFastbreak',
    address: 'Koppenstr.8(Ostbahnhof)',
    stars: 2,
    note: '-',
    lastupdate: '2014-03-05',
    pin: { type: 'Point', coordinates: [ 13.4343831, 52.5128869 ] },
    country: 'Germany',
    street: 'Koppenstraße',
    number: '8' },
  { city: 'Berlin',
    zipcode: '12109',
    place: 'MariendorferKäfer',
    machine: 'AddamsFamilyGold',
    address: 'MariendorferDamm100',
    stars: 3,
    note: 'Neu5Flipperhier',
    lastupdate: '2013-11-22',
    pin: { type: 'Point', coordinates: [ 13.3834788, 52.4438003 ] },
    country: 'Germany',
    street: 'Mariendorfer Damm',
    number: '100' },
  { city: 'Berlin',
    zipcode: '10999',
    place: 'MöbelOlfe',
    machine: 'PiratesoftheCaribbean',
    address: 'ReichenbergerStr.177',
    stars: 3,
    note: 'In-Kneipe,immersehrvoll,Flipperkaummöglich',
    lastupdate: '2012-11-06',
    pin: { type: 'Point', coordinates: [ 13.41734, 52.50002 ] },
    country: 'Germany',
    street: 'Reichenberger Straße',
    number: '177' },
  { city: 'Berlin',
    zipcode: '10245',
    place: 'Feuermelder',
    machine: 'MedievalMadness',
    address: 'Gärtnerstr.(BoxhagenerPlatz)',
    stars: 3,
    note: 'RaucherkneipeFarbdisplay',
    lastupdate: '2013-01-17',
    pin: { type: 'Point', coordinates: [ 13.4606017, 52.5102236 ] },
    country: 'Germany',
    street: 'Gärtnerstraße',
    number: null },
  { city: 'Berlin',
    zipcode: '10999',
    place: 'Franken',
    machine: 'AC/DCPro',
    address: 'Oranienstr.19,gegenüberSo36',
    stars: 3,
    note: 'reinigen,spieltgut.http://franken-bar.de',
    lastupdate: '2012-09-04',
    pin: { type: 'Point', coordinates: [ 13.4272009, 52.4956904 ] },
    country: 'Germany',
    street: null,
    number: null },
  { city: 'Berlin',
    zipcode: '10999',
    place: 'Travolta',
    machine: 'WHOdunnit',
    address: 'WienerStraße14b',
    stars: 3,
    note: '-',
    lastupdate: '2013-05-13',
    pin: { type: 'Point', coordinates: [ 13.42902, 52.4981 ] },
    country: 'Germany',
    street: 'Wiener Straße',
    number: '14B' },
  { city: 'Berlin',
    zipcode: '10999',
    place: 'MisfitBar',
    machine: 'AddamsFamily',
    address: 'Leuschnerdamm41',
    stars: 3,
    note: '-',
    lastupdate: '2013-02-28',
    pin: { type: 'Point', coordinates: [ 13.4169764, 52.503105 ] },
    country: 'Germany',
    street: 'Leuschnerdamm',
    number: '41' },
  { city: 'Berlin',
    zipcode: '12435',
    place: 'WhiteTrash',
    machine: 'AddamsFamily',
    address: 'Flutgraben2',
    stars: 0,
    note: 'derzeitnichtinderAufstellung',
    lastupdate: '2014-07-09',
    pin: { type: 'Point', coordinates: [ 13.4515662, 52.4970164 ] },
    country: 'Germany',
    street: 'Am Flutgraben',
    number: '2' },
  { city: 'Berlin',
    zipcode: '13509',
    place: 'ZurHütte',
    machine: 'ScaredStiff',
    address: 'Mieraustraße(EckeErnststraße)',
    stars: 0,
    note: 'Reinickendorf',
    lastupdate: '2012-07-03',
    pin: { type: 'Point', coordinates: [ 13.3083162, 52.5849482 ] },
    country: 'Germany',
    street: 'Miraustraße',
    number: null },
  { city: 'Berlin',
    zipcode: '10437',
    place: 'Fengler',
    machine: 'AddamsFamily',
    address: 'LychenerStr.',
    stars: 2,
    note: '-',
    lastupdate: '2012-07-06',
    pin: { type: 'Point', coordinates: [ 13.4177592, 52.5439235 ] },
    country: 'Germany',
    street: 'Lychener Straße',
    number: null },
  { city: 'Berlin',
    zipcode: '12109',
    place: 'MariendorferKäfer',
    machine: 'MonsterBash',
    address: 'MariendorferDamm100',
    stars: 3,
    note: 'Neu5Flipperhier',
    lastupdate: '2013-11-22',
    pin: { type: 'Point', coordinates: [ 13.3834788, 52.4438003 ] },
    country: 'Germany',
    street: 'Mariendorfer Damm',
    number: '100' },
  { city: 'Berlin',
    zipcode: '13467',
    place: 'WirtshausamFliess',
    machine: 'MataHari',
    address: 'BerlinerStr',
    stars: 2,
    note: 'Raucherkneipe',
    lastupdate: '2008-10-03',
    pin:
     { type: 'Point',
       coordinates: [ 13.3136194, 52.61996389999999 ] },
    country: 'Germany',
    street: 'Berliner Straße',
    number: null },
  { city: 'Berlin',
    zipcode: '12043',
    place: 'Cineplex-NeuköllnArkaden',
    machine: 'TalesoftheArabianNights',
    address: 'Karl-Marx-Str.66',
    stars: 2,
    note: '3Flipper,Spielfeldtotalverdreckt,abergutspielbar.SkillshotausschließlichaufdenmittlerenTopf',
    lastupdate: '2013-12-09',
    pin: { type: 'Point', coordinates: [ 13.432996, 52.4821579 ] },
    country: 'Germany',
    street: 'Karl-Marx-Straße',
    number: '66' },
  { city: 'Berlin',
    zipcode: '12163',
    place: 'Sterntaler',
    machine: 'Dracula',
    address: 'Schildhornstraße64',
    stars: 3,
    note: 'NetteAtmosphäre.Flippersuperspielbar,könntemalgereinigtunddefekteLampenersetztwerden.',
    lastupdate: '2014-07-09',
    pin: { type: 'Point', coordinates: [ 13.3148649, 52.4647078 ] },
    country: 'Germany',
    street: 'Schildhornstraße',
    number: '64' },
  { city: 'Berlin',
    zipcode: '12043',
    place: 'Cineplex-NeuköllnArkaden',
    machine: 'WorldPokerTour',
    address: 'Karl-Marx-Str.66',
    stars: 0,
    note: '3Flipper',
    lastupdate: '2013-12-09',
    pin: { type: 'Point', coordinates: [ 13.432996, 52.4821579 ] },
    country: 'Germany',
    street: 'Karl-Marx-Straße',
    number: '66' },
  { city: 'Berlin',
    zipcode: '12105',
    place: 'Bier-Stübl',
    machine: 'FishTales',
    address: 'MariendorferDamm86',
    stars: 3,
    note: 'Raucherkneipe',
    lastupdate: '2013-10-27',
    pin: { type: 'Point', coordinates: [ 13.38548, 52.44498000000001 ] },
    country: 'Germany',
    street: 'Mariendorfer Damm',
    number: '86' },
  { city: 'Berlin',
    zipcode: '10999',
    place: 'Monarch',
    machine: 'Dracula',
    address: 'Skalitzerstr.134',
    stars: 3,
    note: '-',
    lastupdate: '2012-11-06',
    pin: { type: 'Point', coordinates: [ 13.4204973, 52.4992667 ] },
    country: 'Germany',
    street: 'Skalitzer Straße',
    number: '134' },
  { city: 'Berlin',
    zipcode: '10997',
    place: 'Milchbar',
    machine: 'StarTrek',
    address: 'Manteuffelstr.41',
    stars: 3,
    note: '-',
    lastupdate: '2013-05-31',
    pin: { type: 'Point', coordinates: [ 13.4266988, 52.4997793 ] },
    country: 'Germany',
    street: 'Manteuffelstraße',
    number: '41' },
  { city: 'Berlin',
    zipcode: '10625',
    place: 'WirtshausWuppke',
    machine: 'AttackfromMars',
    address: 'Schlüterstraße21',
    stars: 2,
    note: 'Raucher-Bier-Kneipe,Flippersoundabgeschaltet,tiltetkaum.',
    lastupdate: '2008-12-29',
    pin: { type: 'Point', coordinates: [ 13.31714, 52.50666 ] },
    country: 'Germany',
    street: 'Schlüterstraße',
    number: '21' },
  { city: 'Berlin',
    zipcode: '10???',
    place: 'S-Bahn-Klause',
    machine: 'Dracula',
    address: 'Kaiser-Willhelm-Str.',
    stars: 1,
    note: 'leiderbeideDefektSchadeausserdemsehrteuerda',
    lastupdate: '2009-02-27',
    pin: { type: 'Point', coordinates: [ 13.33453, 52.43059 ] },
    country: 'Germany',
    street: 'Kaiser-Wilhelm-Straße',
    number: '10' },
  { city: 'Berlin',
    zipcode: '10961',
    place: 'CafeLogo',
    machine: 'MetallicaLE',
    address: 'Blücherstr.61',
    stars: 3,
    note: '-',
    lastupdate: '2013-10-10',
    pin: { type: 'Point', coordinates: [ 13.40003, 52.49469 ] },
    country: 'Germany',
    street: 'Blücherstraße',
    number: '61' },
  { city: 'Berlin',
    zipcode: '10437',
    place: 'Mokum',
    machine: 'AdamsFamily',
    address: 'DanzigerStr.EckeKollwitzstr.',
    stars: 2,
    note: 'netteKneipemitKicker,Konzerten...',
    lastupdate: '2009-08-21',
    pin: { type: 'Point', coordinates: [ 13.4072944, 52.5455109 ] },
    country: 'Germany',
    street: null,
    number: null },
  { city: 'Berlin',
    zipcode: '13403',
    place: 'ChillOutBar',
    machine: 'LordoftheRings',
    address: 'General-Barby-Str.25',
    stars: 2,
    note: 'netteLocation',
    lastupdate: '2013-07-06',
    pin: { type: 'Point', coordinates: [ 13.31674, 52.56879 ] },
    country: 'Germany',
    street: 'General-Barby-Straße',
    number: '25' },
  { city: 'Berlin',
    zipcode: '10787',
    place: 'BerolinaBowlingLounge',
    machine: 'Jackbot',
    address: 'Kleiststr.3-6',
    stars: 0,
    note: 'WiederCorvettelautMitarbeiterinMönchengladbach,wirdwohlsoschnellnichtwiederkommen...',
    lastupdate: '2014-06-02',
    pin: { type: 'Point', coordinates: [ 13.35169, 52.50041 ] },
    country: 'Germany',
    street: 'Kleiststraße',
    number: '3' },
  { city: 'Berlin',
    zipcode: '10245',
    place: 'Feuermelder',
    machine: 'AC/DCLE',
    address: 'KrossenerStraße24',
    stars: 3,
    note: 'topZustand!',
    lastupdate: '2013-09-17',
    pin: { type: 'Point', coordinates: [ 13.4601458, 52.5102003 ] },
    country: 'Germany',
    street: 'Krossener Straße',
    number: '24' },
  { city: 'Berlin',
    zipcode: '10179',
    place: 'Engelchen',
    machine: 'AddamsFamily',
    address: 'Engeldamm/Adalbertstr.',
    stars: 2,
    note: 'kneipegibtesnichtmehr',
    lastupdate: '2011-10-28',
    pin: { type: 'Point', coordinates: [ 13.4232912, 52.5069017 ] },
    country: 'Germany',
    street: 'Adalbertstraße',
    number: null },
  { city: 'Berlin',
    zipcode: '10178',
    place: 'BowlingamAlex',
    machine: 'Terminator3',
    address: 'Rathausstraße5(indenRathauspassagenamAlexanderplatz)',
    stars: 1,
    note: 'Abgerockt',
    lastupdate: '2013-09-24',
    pin: { type: 'Point', coordinates: [ 13.410337, 52.51952439999999 ] },
    country: 'Germany',
    street: 'Rathausstraße',
    number: '5' },
  { city: 'Berlin',
    zipcode: '10961',
    place: 'Clash',
    machine: 'AddamsFamilyGold',
    address: 'Gneisenaustr.2a',
    stars: 3,
    note: '-',
    lastupdate: '2013-12-17',
    pin: { type: 'Point', coordinates: [ 13.38817, 52.49191 ] },
    country: 'Germany',
    street: 'Gneisenaustraße',
    number: '2A' },
  { city: 'Berlin',
    zipcode: '12107',
    place: 'Hanniball',
    machine: 'MedievalMadness',
    address: 'TempelhoferHafen',
    stars: 3,
    note: 'Billardcenter',
    lastupdate: '2012-10-22',
    pin: { type: 'Point', coordinates: [ 13.3841611, 52.4568424 ] },
    country: 'Germany',
    street: 'Tempelhofer Damm',
    number: '215' },
  { city: 'Berlin',
    zipcode: '13509',
    place: 'Eulenspiegel',
    machine: 'Maverick-TheMovie',
    address: 'WaidmannslusterDamm50',
    stars: 3,
    note: 'Fußballtreffpunkt,netteKneipe+Bewirtung',
    lastupdate: '2009-05-28',
    pin: { type: 'Point', coordinates: [ 13.2979803, 52.5980646 ] },
    country: 'Germany',
    street: 'Waidmannsluster Damm',
    number: '50' },
  { city: 'Berlin',
    zipcode: '12435',
    place: 'WhiteTrash',
    machine: 'MedievalMadness',
    address: 'Flutgraben2',
    stars: 0,
    note: 'derzeitnichtinderAufstellung',
    lastupdate: '2014-07-09',
    pin: { type: 'Point', coordinates: [ 13.4515662, 52.4970164 ] },
    country: 'Germany',
    street: 'Am Flutgraben',
    number: '2' },
  { city: 'Berlin',
    zipcode: '13585',
    place: 'dieWampe',
    machine: 'GrandPrix',
    address: 'Bismarkstr.60',
    stars: 3,
    note: 'GeileSceneRockKneipeinSpandauab19Uhroffenbismorgens,www.diewampe.de',
    lastupdate: '2005-12-10',
    pin: { type: 'Point', coordinates: [ 13.2034001, 52.5422473 ] },
    country: 'Germany',
    street: 'Bismarckstraße',
    number: '60' },
  { city: 'Berlin',
    zipcode: '10961',
    place: 'Clash',
    machine: 'X-MenLE',
    address: 'Gneisenaustr.2a',
    stars: 3,
    note: '-',
    lastupdate: '2013-12-17',
    pin: { type: 'Point', coordinates: [ 13.38817, 52.49191 ] },
    country: 'Germany',
    street: 'Gneisenaustraße',
    number: '2A' },
  { city: 'Berlin',
    zipcode: '13405',
    place: 'Raucherkneipe"Daggi\'sEinflug1"',
    machine: 'LordoftheRings',
    address: 'Scharnweberstraße37',
    stars: 0,
    note: '1Spiel50Cent,5Spiele2Euro',
    lastupdate: '2011-02-03',
    pin: { type: 'Point', coordinates: [ 13.32064, 52.56612 ] },
    country: 'Germany',
    street: 'Scharnweberstraße',
    number: '37' },
  { city: 'Berlin',
    zipcode: '10407',
    place: 'Unendlich',
    machine: 'IndianaJones',
    address: 'Boetzowstr.14',
    stars: 3,
    note: '-',
    lastupdate: '2010-12-06',
    pin: { type: 'Point', coordinates: [ 13.43235, 52.53001 ] },
    country: 'Germany',
    street: 'Bötzowstraße',
    number: '14' },
  { city: 'Berlin',
    zipcode: '10245',
    place: 'GrosseFreiheit114',
    machine: 'Congo',
    address: 'BoxhagenerStrasse114',
    stars: 3,
    note: 'SchwuleKiezkneipe,Zustandprima!',
    lastupdate: '2010-01-18',
    pin: { type: 'Point', coordinates: [ 13.4559811, 52.5135996 ] },
    country: 'Germany',
    street: 'Boxhagener Straße',
    number: '114' },
  { city: 'Berlin',
    zipcode: '12049',
    place: 'Syndikat',
    machine: 'AddamsFamilyGold',
    address: 'Weisestr.56',
    stars: 3,
    note: '-',
    lastupdate: '2013-09-17',
    pin: { type: 'Point', coordinates: [ 13.42402, 52.47823 ] },
    country: 'Germany',
    street: 'Weisestraße',
    number: '56' },
  { city: 'Berlin',
    zipcode: '10965',
    place: 'Golgatha',
    machine: 'X-MenLE',
    address: 'Dudenstr.48',
    stars: 3,
    note: '-',
    lastupdate: '2013-04-03',
    pin: { type: 'Point', coordinates: [ 13.37698, 52.48543 ] },
    country: 'Germany',
    street: 'Dudenstraße',
    number: '48' },
  { city: 'Berlin',
    zipcode: '10245',
    place: 'Sport-Treff',
    machine: 'JunkYard',
    address: 'Corinthstr.',
    stars: 0,
    note: 'Altmännerkneipe',
    lastupdate: '2009-01-27',
    pin: { type: 'Point', coordinates: [ 13.4605027, 52.5003044 ] },
    country: 'Germany',
    street: 'Corinthstraße',
    number: null },
  { city: 'Berlin',
    zipcode: '10965',
    place: 'Yorckschlößchen',
    machine: 'AddamsFamily',
    address: 'Yorckstr.',
    stars: 1,
    note: 'linkerFlipperlahm,kaumbeleuchtet,',
    lastupdate: '2005-10-03',
    pin: { type: 'Point', coordinates: [ 13.3777991, 52.4920157 ] },
    country: 'Germany',
    street: 'Yorckstraße',
    number: null },
  { city: 'Berlin',
    zipcode: '10245',
    place: 'AstroBar',
    machine: 'AttackfromMars',
    address: 'Simon-Dach-Str.40',
    stars: 3,
    note: '-outlaneswide',
    lastupdate: '2014-01-06',
    pin: { type: 'Point', coordinates: [ 13.4572878, 52.5119485 ] },
    country: 'Germany',
    street: 'Simon-Dach-Straße',
    number: '40' },
  { city: 'Berlin',
    zipcode: '10245',
    place: 'Glühlampe',
    machine: 'Sopranos',
    address: 'Lehmbruckstr.EckeRochowstr.',
    stars: 3,
    note: '-',
    lastupdate: '2006-04-18',
    pin: { type: 'Point', coordinates: [ 13.4554471, 52.5019332 ] },
    country: 'Germany',
    street: null,
    number: null },
  { city: 'Berlin',
    zipcode: '13509',
    place: 'Eulenspiegel',
    machine: 'StarWars',
    address: 'WaidmannslusterDamm50',
    stars: 3,
    note: 'Fußballtreffpunkt,netteKneipe+Bewirtung',
    lastupdate: '2009-06-04',
    pin: { type: 'Point', coordinates: [ 13.2979803, 52.5980646 ] },
    country: 'Germany',
    street: 'Waidmannsluster Damm',
    number: '50' },
  { city: 'Berlin',
    zipcode: '13595',
    place: 'PlanB',
    machine: 'AttackfromMars',
    address: 'Wilhelmstrasse144',
    stars: 3,
    note: 'GutinSchuss!JungesPublikumhier.',
    lastupdate: '2014-04-23',
    pin: { type: 'Point', coordinates: [ 13.1926402, 52.5240081 ] },
    country: 'Germany',
    street: 'Wilhelmstraße',
    number: '144' },
  { city: 'Berlin',
    zipcode: '10245',
    place: 'Habermeyer',
    machine: 'AC/DC',
    address: 'Gärtnerstr.6',
    stars: 3,
    note: 'AllesinOrdnungwieneu.LeiderSoundaufganzganzleisegestellt.NetteBedienungundLokation,leiderRaucherkneipe.',
    lastupdate: '2013-12-09',
    pin: { type: 'Point', coordinates: [ 13.4602801, 52.5093329 ] },
    country: 'Germany',
    street: 'Gärtnerstraße',
    number: '6' },
  { city: 'Berlin',
    zipcode: '12247',
    place: 'PViewBillard&Events',
    machine: 'MedievalMadness',
    address: 'Kaiser-Wilhelm-Str.29',
    stars: 3,
    note: 'NetterLadenauchfürBillardundSnooker',
    lastupdate: '2014-01-28',
    pin: { type: 'Point', coordinates: [ 13.3378, 52.43143999999999 ] },
    country: 'Germany',
    street: 'Kaiser-Wilhelm-Straße',
    number: '29' },
  { city: 'Berlin',
    zipcode: '10245',
    place: 'Feuermelder',
    machine: 'RevengefromMars',
    address: 'Gärtnerstr.(BoxhagenerPlatz)',
    stars: 3,
    note: '-',
    lastupdate: '2014-01-01',
    pin: { type: 'Point', coordinates: [ 13.4606017, 52.5102236 ] },
    country: 'Germany',
    street: 'Gärtnerstraße',
    number: null },
  { city: 'Berlin',
    zipcode: '10999',
    place: 'Route36',
    machine: 'AttackfromMars',
    address: 'LausitzerStr.1',
    stars: 3,
    note: '-',
    lastupdate: '2013-12-19',
    pin: { type: 'Point', coordinates: [ 13.43001, 52.49901 ] },
    country: 'Germany',
    street: 'Lausitzer Straße',
    number: '1' },
  { city: 'Berlin',
    zipcode: '13403',
    place: 'ChillOutBar',
    machine: 'TheatreofMagic',
    address: 'General-Barby-Str.25',
    stars: 3,
    note: 'netteLocation',
    lastupdate: '2012-07-25',
    pin: { type: 'Point', coordinates: [ 13.31674, 52.56879 ] },
    country: 'Germany',
    street: 'General-Barby-Straße',
    number: '25' },
  { city: 'Berlin',
    zipcode: '10???',
    place: 'WildAtHeart',
    machine: 'HarleyDavidson',
    address: '-',
    stars: 0,
    note: '-',
    lastupdate: '2009-01-31',
    pin: { type: 'Point', coordinates: [ 13.4435675, 52.509679 ] },
    country: 'Germany',
    street: null,
    number: null },
  { city: 'Berlin',
    zipcode: '10243',
    place: 'EastsideBowling',
    machine: 'IndianaJones',
    address: 'Koppenstraße8(Ostbahnhof)',
    stars: 3,
    note: '-',
    lastupdate: '2012-07-25',
    pin: { type: 'Point', coordinates: [ 13.4343831, 52.5128869 ] },
    country: 'Germany',
    street: 'Koppenstraße',
    number: '8' },
  { city: 'Berlin',
    zipcode: '10997',
    place: 'Milchbar',
    machine: 'ScaredStiff',
    address: 'Manteuffelstr.41',
    stars: 2,
    note: '-',
    lastupdate: '2011-09-28',
    pin: { type: 'Point', coordinates: [ 13.4266988, 52.4997793 ] },
    country: 'Germany',
    street: 'Manteuffelstraße',
    number: '41' },
  { city: 'Berlin',
    zipcode: '10245',
    place: 'AstroBar',
    machine: 'SternStarTrekLE',
    address: 'Simon-Dach-Str.40',
    stars: 3,
    note: 'Nagelneu!Super!',
    lastupdate: '2014-01-15',
    pin: { type: 'Point', coordinates: [ 13.4572878, 52.5119485 ] },
    country: 'Germany',
    street: 'Simon-Dach-Straße',
    number: '40' },
  { city: 'Berlin',
    zipcode: '10405',
    place: 'Yesterday',
    machine: 'AdamsFamilyGold',
    address: 'MetzerStraße2',
    stars: 3,
    note: 'TolleLocation',
    lastupdate: '2014-08-14',
    pin: { type: 'Point', coordinates: [ 13.414031, 52.5319869 ] },
    country: 'Germany',
    street: 'Metzer Straße',
    number: '2' },
  { city: 'Berlin',
    zipcode: '10719',
    place: 'Billard-International',
    machine: 'Batman',
    address: 'Knesebeckstr.38',
    stars: 3,
    note: 'wieneu!',
    lastupdate: '2012-05-21',
    pin: { type: 'Point', coordinates: [ 13.32118, 52.50091 ] },
    country: 'Germany',
    street: 'Knesebeckstraße',
    number: '38' },
  { city: 'Berlin',
    zipcode: '12435',
    place: 'WhiteTrash',
    machine: 'StarTrek:TheNextGeneration',
    address: 'Flutgraben2',
    stars: 0,
    note: 'derzeitnichtinderAufstellung',
    lastupdate: '2014-07-09',
    pin: { type: 'Point', coordinates: [ 13.4515662, 52.4970164 ] },
    country: 'Germany',
    street: 'Am Flutgraben',
    number: '2' },
  { city: 'Berlin',
    zipcode: '10787',
    place: 'BerolinaBowlingLounge',
    machine: 'Corvette',
    address: 'Kleiststr.3-6',
    stars: 0,
    note: 'Immernochweg,lautMitarbeiterinMönchenGladbach?obderwiderkommt,istwohlfraglich.Schade',
    lastupdate: '2014-06-02',
    pin: { type: 'Point', coordinates: [ 13.35169, 52.50041 ] },
    country: 'Germany',
    street: 'Kleiststraße',
    number: '3' },
  { city: 'Berlin',
    zipcode: '12247',
    place: 'PViewBillard&Events',
    machine: 'MonsterBash',
    address: 'Kaiser-Wilhelm-Str.29',
    stars: 3,
    note: 'NetterLadenauchfürBillardundSnooker',
    lastupdate: '2014-01-28',
    pin: { type: 'Point', coordinates: [ 13.3378, 52.43143999999999 ] },
    country: 'Germany',
    street: 'Kaiser-Wilhelm-Straße',
    number: '29' },
  { city: 'Berlin',
    zipcode: '12435',
    place: 'WhiteTrash',
    machine: 'JudgeDredd',
    address: 'Flutgraben2',
    stars: 3,
    note: 'imTatooStudio',
    lastupdate: '2014-06-24',
    pin: { type: 'Point', coordinates: [ 13.4515662, 52.4970164 ] },
    country: 'Germany',
    street: 'Am Flutgraben',
    number: '2' },
  { city: 'Berlin/PrenzlauerBerg',
    zipcode: '10405',
    place: 'YesterdayfrüherFlowerPower',
    machine: 'AddamsFamilyGold',
    address: 'SenefelderPlatz',
    stars: 1,
    note: 'derFlipperistToT,Locationistnett',
    lastupdate: '2010-11-11',
    pin: { type: 'Point', coordinates: [ 13.4128709, 52.5320505 ] },
    country: 'Germany',
    street: null,
    number: null },
  { city: 'Berlin-Hönow',
    zipcode: '15366',
    place: 'CasinoGlückspilz',
    machine: 'NoFear',
    address: 'AltlandsbergerChaussee7',
    stars: 3,
    note: '7Flipperhier,FlipperingutemZustand.',
    lastupdate: '2013-05-31',
    pin: { type: 'Point', coordinates: [ 13.64419, 52.54464 ] },
    country: 'Germany',
    street: 'Altlandsberger Chaussee',
    number: '7' },
  { city: 'Berlin-Hönow',
    zipcode: '15366',
    place: 'CasinoGlückspilz',
    machine: 'CirqusVoltaire',
    address: 'AltlandsbergerChaussee7',
    stars: 2,
    note: '-',
    lastupdate: '2014-06-25',
    pin: { type: 'Point', coordinates: [ 13.64419, 52.54464 ] },
    country: 'Germany',
    street: 'Altlandsberger Chaussee',
    number: '7' },
  { city: 'Berlin-Hönow',
    zipcode: '15366',
    place: 'CasinoGlückspilz',
    machine: 'NoGoodGofers',
    address: 'AltlandsbergerChaussee7',
    stars: 2,
    note: 'Abschussschwach',
    lastupdate: '2013-05-13',
    pin: { type: 'Point', coordinates: [ 13.64419, 52.54464 ] },
    country: 'Germany',
    street: 'Altlandsberger Chaussee',
    number: '7' },
  { city: 'Berlin-Hönow',
    zipcode: '15366',
    place: 'CasinoGlückspilz',
    machine: 'CSI',
    address: 'AltlandsbergerChaussee7',
    stars: 3,
    note: '7Flipperhier!',
    lastupdate: '2013-05-31',
    pin: { type: 'Point', coordinates: [ 13.64419, 52.54464 ] },
    country: 'Germany',
    street: 'Altlandsberger Chaussee',
    number: '7' },
  { city: 'Berlin-Hönow',
    zipcode: '15366',
    place: 'CasinoGlückspilz',
    machine: 'RevengefromMars',
    address: 'AltlandsbergerChaussee7',
    stars: 3,
    note: '7Flipperhier!',
    lastupdate: '2014-08-11',
    pin: { type: 'Point', coordinates: [ 13.64419, 52.54464 ] },
    country: 'Germany',
    street: 'Altlandsberger Chaussee',
    number: '7' },
  { city: 'Berlin-Hönow',
    zipcode: '15366',
    place: 'CasinoGlückspilz',
    machine: 'AVATAR',
    address: 'AltlandsbergerChaussee7',
    stars: 3,
    note: '7Flipperhier,extraRaumfürFlipper,superZustand',
    lastupdate: '2014-08-11',
    pin: { type: 'Point', coordinates: [ 13.64419, 52.54464 ] },
    country: 'Germany',
    street: 'Altlandsberger Chaussee',
    number: '7' },
  { city: 'Berlin-Hönow',
    zipcode: '15366',
    place: 'CasinoGlückspilz',
    machine: 'Terminator2',
    address: 'AltlandsbergerChaussee7',
    stars: 3,
    note: '7Flipperhier',
    lastupdate: '2014-08-11',
    pin: { type: 'Point', coordinates: [ 13.64419, 52.54464 ] },
    country: 'Germany',
    street: 'Altlandsberger Chaussee',
    number: '7' },
  { city: 'Berlin-Kreuzberg',
    zipcode: '10967',
    place: 'CafeNova',
    machine: 'TransformersLE',
    address: 'Urbanstr.30',
    stars: 3,
    note: '-',
    lastupdate: '2012-10-22',
    pin: { type: 'Point', coordinates: [ 13.4135, 52.49138000000001 ] },
    country: 'Germany',
    street: 'Urbanstraße',
    number: '30' },
  { city: 'Berlin',
    zipcode: '12109',
    place: 'MariendorferKäfer',
    machine: 'AvengersLE',
    address: 'MariendorferDamm100',
    stars: 3,
    note: 'Neu5Flipperhier',
    lastupdate: '2013-11-22',
    pin: { type: 'Point', coordinates: [ 13.3834788, 52.4438003 ] },
    country: 'Germany',
    street: 'Mariendorfer Damm',
    number: '100' },
  { city: 'Berlin',
    zipcode: '12043',
    place: 'Cineplex-NeuköllnArkaden',
    machine: 'WheelofFortune',
    address: 'Karl-Marx-Str.66',
    stars: 0,
    note: '3Flipper',
    lastupdate: '2013-12-09',
    pin: { type: 'Point', coordinates: [ 13.432996, 52.4821579 ] },
    country: 'Germany',
    street: 'Karl-Marx-Straße',
    number: '66' },
  { city: 'Berlin',
    zipcode: '10117',
    place: 'Zosch',
    machine: 'LordoftheRings',
    address: 'Tucholskystr.30',
    stars: 3,
    note: '-',
    lastupdate: '2011-01-21',
    pin: { type: 'Point', coordinates: [ 13.39382, 52.52601 ] },
    country: 'Germany',
    street: 'Tucholskystraße',
    number: '30' },
  { city: 'Berlin',
    zipcode: '10117',
    place: 'BaxpaxHostel',
    machine: 'TheatreofMagic',
    address: 'Ziegelstr.28',
    stars: 2,
    note: 'ImAufenthaltsraum',
    lastupdate: '2013-09-25',
    pin: { type: 'Point', coordinates: [ 13.39095, 52.52374 ] },
    country: 'Germany',
    street: 'Ziegelstraße',
    number: '28' },
  { city: 'Berlin',
    zipcode: '10997',
    place: 'Trinkteufel',
    machine: 'Metallica',
    address: 'Naunynstr.60',
    stars: 3,
    note: '-',
    lastupdate: '2013-08-22',
    pin: { type: 'Point', coordinates: [ 13.4202207, 52.5020719 ] },
    country: 'Germany',
    street: 'Naunynstraße',
    number: '60' },
  { city: 'Berlin',
    zipcode: '12109',
    place: 'MariendorferKäfer',
    machine: 'MedievalMadness',
    address: 'MariendorferDamm100',
    stars: 3,
    note: 'Neu5Flipperhier',
    lastupdate: '2013-11-22',
    pin: { type: 'Point', coordinates: [ 13.3834788, 52.4438003 ] },
    country: 'Germany',
    street: 'Mariendorfer Damm',
    number: '100' },
  { city: 'Berlin',
    zipcode: '10999',
    place: 'WeißeTaube',
    machine: 'Tron',
    address: 'WienerStr.15',
    stars: 3,
    note: 'Kreuzberg',
    lastupdate: '2013-11-22',
    pin: { type: 'Point', coordinates: [ 13.42966, 52.49795 ] },
    country: 'Germany',
    street: 'Wiener Straße',
    number: '15' },
  { city: 'Berlin',
    zipcode: '10627',
    place: 'DIO´sMusikcafé',
    machine: 'Terminator2',
    address: 'Schillerstraße44',
    stars: 2,
    note: 'BeleuchtunglinkeSeitespärlich,Raucherkneipe',
    lastupdate: '2014-03-23',
    pin: { type: 'Point', coordinates: [ 13.3054942, 52.5100017 ] },
    country: 'Germany',
    street: 'Schillerstraße',
    number: '44' },
  { city: 'Berlin',
    zipcode: '10243',
    place: 'EastsideBowling',
    machine: 'DemolitionMan',
    address: 'Koppenstraße8(Ostbahnhof)',
    stars: 3,
    note: 'Cranez.Zt.defekt.',
    lastupdate: '2014-03-23',
    pin: { type: 'Point', coordinates: [ 13.4343831, 52.5128869 ] },
    country: 'Germany',
    street: 'Koppenstraße',
    number: '8' },
  { city: 'Berlin',
    zipcode: '10435',
    place: 'BASSYClub',
    machine: 'TheAddamsFamily',
    address: 'SchönhauserAllee',
    stars: 0,
    note: '-',
    lastupdate: '2013-08-22',
    pin: { type: 'Point', coordinates: [ 13.4120874, 52.5376838 ] },
    country: 'Germany',
    street: 'Schönhauser Allee',
    number: null },
  { city: 'Berlin',
    zipcode: '12109',
    place: 'MariendorferKäfer',
    machine: 'Ripley`sBelieveitornot',
    address: 'MariendorferDamm100',
    stars: 3,
    note: 'Neu5Flipperhier',
    lastupdate: '2013-11-22',
    pin: { type: 'Point', coordinates: [ 13.3834788, 52.4438003 ] },
    country: 'Germany',
    street: 'Mariendorfer Damm',
    number: '100' },
  { city: 'Berlin',
    zipcode: '10247',
    place: 'Spielhalle',
    machine: 'TheGetaway',
    address: 'Ebertystr.',
    stars: 0,
    note: 'nebenKneipeBudike(?)',
    lastupdate: '2010-01-22',
    pin: { type: 'Point', coordinates: [ 13.4528909, 52.5241451 ] },
    country: 'Germany',
    street: 'Ebertystraße',
    number: null },
  { city: 'Berlin',
    zipcode: '10435',
    place: 'BASSYClub',
    machine: 'Elvis',
    address: 'SchönhauserAllee',
    stars: 3,
    note: '-',
    lastupdate: '2012-03-22',
    pin: { type: 'Point', coordinates: [ 13.4120874, 52.5376838 ] },
    country: 'Germany',
    street: 'Schönhauser Allee',
    number: null },
  { city: 'Berlin',
    zipcode: '10245',
    place: 'RockZ',
    machine: 'VirtualPinball',
    address: 'Simon-DachStr.37',
    stars: 0,
    note: 'zurZeitleiderdefekt!IstdaseinFlipper?Geschmacksache!',
    lastupdate: '2009-09-30',
    pin: { type: 'Point', coordinates: [ 13.4566414, 52.5104218 ] },
    country: 'Germany',
    street: 'Simon-Dach-Straße',
    number: '37' },
  { city: 'Berlin',
    zipcode: '10405',
    place: 'BierstubezurLinde',
    machine: 'MedievalMadness',
    address: 'PrenzlauerAllee,EckeDanzigerStrasse',
    stars: 3,
    note: 'MedievalMadnessläuftsehrgut,Addamsistsehrdunkelundschlechtzuspielen.GünstigePreiseundnetteBedienung',
    lastupdate: '2009-12-29',
    pin:
     { type: 'Point',
       coordinates: [ 13.4230065, 52.53419359999999 ] },
    country: 'Germany',
    street: null,
    number: null },
  { city: 'Berlin',
    zipcode: '10245',
    place: 'Irrenhaus',
    machine: 'Terminator3',
    address: 'Markgrafendamm36',
    stars: 3,
    note: '-',
    lastupdate: '2013-09-17',
    pin: { type: 'Point', coordinates: [ 13.465148, 52.4982046 ] },
    country: 'Germany',
    street: 'Markgrafendamm',
    number: '36' },
  { city: 'Berlin',
    zipcode: '10245',
    place: 'Irrenhaus',
    machine: 'Terminator3',
    address: 'Markgrafendamm36',
    stars: 2,
    note: 'EckeStralauerAllee',
    lastupdate: '2014-04-23',
    pin: { type: 'Point', coordinates: [ 13.465148, 52.4982046 ] },
    country: 'Germany',
    street: 'Markgrafendamm',
    number: '36' },
  { city: 'Berlin',
    zipcode: '10999',
    place: 'Bohnengold(?)',
    machine: 'Funhouse',
    address: 'ReichenbergerStraße153',
    stars: 2,
    note: 'DisplayhatabundzuFehler,PlungerohneKraft.DunkleRaucherkneipeab17.00',
    lastupdate: '2014-04-15',
    pin: { type: 'Point', coordinates: [ 13.4242, 52.49762 ] },
    country: 'Germany',
    street: 'Reichenberger Straße',
    number: '153' },
  { city: 'Berlin',
    zipcode: '10???',
    place: 'Abgedreht',
    machine: 'AddamsFamily',
    address: 'KarlMarxalle140',
    stars: 3,
    note: 'sehenswerteLocation',
    lastupdate: '2010-11-11',
    pin: { type: 'Point', coordinates: [ 13.45222, 52.51573 ] },
    country: 'Germany',
    street: 'Karl-Marx-Allee',
    number: '140' },
  { city: 'Berlin',
    zipcode: '13403',
    place: 'ChillOutBar',
    machine: 'TwilightZone',
    address: 'General-Barby-Str.25',
    stars: 2,
    note: 'Lockfastunmöglich,allespulenextremvielpower..brutalschnell:-)AbersuperLocation',
    lastupdate: '2013-07-06',
    pin: { type: 'Point', coordinates: [ 13.31674, 52.56879 ] },
    country: 'Germany',
    street: 'General-Barby-Straße',
    number: '25' } ]

document.body.innerHTML = JSON.stringify(a);
